name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: WatchersWorld/watchersworld.client
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'
      - name: Set up client environment
        run: |
          echo "export const environment = {
            production: true,
            appUrl: '${{ secrets.APP_URL }}',
            userKey: '${{ secrets.USER_KEY }}'
          };" > ./src/environments/environment.prod.ts
      - name: Install dependencies
        run: npm install   
      - name: Build client
        run: npm run build -- --output-path=dist

  deploy_client:
    runs-on: ubuntu-latest
    needs: build_client
    environment:
      name: 'Production'
    steps:
      - name: Deploy client
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'WatchersWorldFrontEnd'
          slot-name: 'Production'
          package: ./dist
          publish-profile: ${{ secrets.CLIENT_PUBLISH_PROFILE }}

  build_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: WatchersWorld/WatchersWorld.Server
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Set up server environment
        run: |
          echo '{
            "AzureAd": {
              "Instance": "${{ secrets.AZURE_AD_INSTANCE }}",
              "Domain": "${{ secrets.AZURE_AD_DOMAIN }}",
              "TenantId": "${{ secrets.AZUREAPPSERVICE_TENANTID_F78ED58CF7954AAE9A59768BCCB3C3FA }}",
              "ClientId": "${{ secrets.AZUREAPPSERVICE_CLIENTID_7EBCA730BA4641B299DA8A042E85F1A6 }}",
              "Scopes": "access_as_user",
              "CallbackPath": "/signin-oidc"
            },
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*",
            "ConnectionStrings": {
              "DefaultConnection": "${{ secrets.AZURE_SQL_SERVER_CONNECTION }}"
            },
            "JWT": {
              "Key": "${{ secrets.JWT_KEY }}",
              "ExpiresInDays": 15,
              "Issuer": "${{ secrets.ISSUER_URL }}",
              "ClientUrl": "${{ secrets.CLIENT_URL }}"
            },
            "Email": {
              "From": "${{ secrets.EMAIL_FROM }}",
              "ApplicationName": "Watchers World",
              "ConfirmEmailPath": "account/confirm-email",
              "ResetPasswordPath": "account/reset-password"
            },
            "MailJet": {
              "ApiKey": "${{ secrets.MAILJET_API_KEY }}",
              "SecretKey": "${{ secrets.MAILJET_SECRET_KEY }}"
            },
            "Google": {
              "ClientId": "${{ secrets.GOOGLE_CLIENT_ID }}"
            }
          }' > ./appsettings.json
      - name: Publish server
        run: dotnet publish -c Release -o ./publish --no-restore

  deploy_server:
    runs-on: ubuntu-latest
    needs: build_server
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: 'WatchersWorld'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.SERVER_PUBLISH_PROFILE }}
